### ISSUE TITLE
"SMS messaging is currently disabled" after installing

### ISSUE THREAD

**Issue by Maruhai** [alexlance/signal-android-classic#5]
Hello, I switched to your releases today. Not wanting to build mine, I used your prebuilts (6.21.3 then upgraded to 6.22.5). I followed the installation process correctly, making a backup, uninstalling, installing yours, then restoring. However I cannot send SMS. What gives? Help would be appreciated.

**Comment by DraikenWeAre** [comment]
I think you're supposed to go to default apps settings in your phone and switch signal to sms from there.

Thats what I did anyway to get it to work.

**Comment by alexlance** [comment]
Just noting the title of this issue - do you actually see an error message like "SMS messaging is currently disabled" ?

**Comment by DraikenWeAre** [comment]
@alexlance btw I know this isn't about the issue, but I've been wanting to thank you for posting your fork of Signal honestly, didn't know how since Github doesn't have DMs.

My laptop is busted and I don't really have money to sort it out which is why I couldn't make my own fork based on your guide.

So just wanna say Thank you.

**Comment by alexlance** [comment]
@DraikenWeAre well that's just a great message to receive! I am so happy it's useful for you.

It still makes me shake my head that I had to go down this pathway to be honest - insane to throw away a feature that was basically their only competitive advantage against whatsapp - and also such a persuasive on-boarding mechanism for getting existing users to convert others into new users - but here we are!

**Comment by DraikenWeAre** [comment]
@alexlance You know before realising I could talk to you on Issues I guess , I was wishing Github had a DM option , because besides wanting to thank you , I wanted to suggest if you could make a space on places like reddit  and twitter where you would post updates about your fork and allow more people to be aware.

I know many people besides myself hate the removal of SMS , even my grandmother uses signal honestly and I feel if enough spread on different social media sites where for this fork of yours maybe Merrideth and Signal would see it was a bad Idea and return the option. 

Maybe I'm being foolishly optimistic but it's just a thought I had honestly.

**Comment by Particpant** [comment]
@Maruhai FWIW, SMS works for me on that version, so it might have to do with your install and not the release.

**Comment by alexlance** [comment]
Just built and installed the latest version 6.26.2 and SMS send and receive still work ok. 
https://github.com/alexlance/signal-android-classic/releases

But as a side note, I made a backup - and tried to use: https://github.com/alexlance/signal-message-exporter to do an export and the bit in the code where it invokes: https://github.com/bepaald/signalbackup-tools just ticked over endlessly (half the day of CPU at 100%). Presumably signalbackup-tools will fix that sooner or later - normally it completes in about 5 minutes.

**Comment by alexlance** [comment]
@Maruhai - just shout out if this is still an issue.
